CREATE TABLE MEMBER (
    NO NUMBER(4) NOT NULL,
    ID VARCHAR2(20) NOT NULL CONSTRAINT MEMBER_PK PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    ZIPCODE NUMBER(10) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    REGDATE DATE
);