<<<<<<< HEAD
  CREATE TABLE "TIS002"."NOTICE" 
   (	"NO" NUMBER(4) NOT NULL CONSTRAINT "NOTICE_PK" PRIMARY KEY, 
	"TITLE" VARCHAR2(100) NOT NULL, 
	"CONTENT" VARCHAR2(2000) NOT NULL, 
	"REGDATE" DATE
   );
   
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방1','적당한 환기 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방2','적당한 손씻기 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방3','적당한 마스크 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방4','적당한 거리두기 필요',SYSDATE);

COMMIT;

SELECT * FROM NOTICE;
=======
CREATE TABLE MEMBER (
    NO NUMBER(4) NOT NULL,
    ID VARCHAR2(20) NOT NULL CONSTRAINT MEMBER_PK PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    ZIPCODE NUMBER(10) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    REGDATE DATE
);
>>>>>>> 65b4c2c29ec96af986240699f7e715bb967e900c
