  CREATE TABLE "TIS002"."NOTICE" 
   (	"NO" NUMBER(4) NOT NULL CONSTRAINT "NOTICE_PK" PRIMARY KEY, 
	"TITLE" VARCHAR2(100) NOT NULL, 
	"CONTENT" VARCHAR2(2000) NOT NULL, 
	"REGDATE" DATE
   );
   
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방1','적당한 환기 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방2','적당한 손씻기 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방3','적당한 마스크 필요',SYSDATE);
INSERT INTO NOTICE VALUES (SEQ_MEMBER.NEXTVAL,'코로나 예방4','적당한 거리두기 필요',SYSDATE);

COMMIT;

SELECT * FROM NOTICE;
